feat: prop to enable or disable clipboard
revolist/revogrid pull request #179
Opened 2021-02-24 21:14 UTC by leyenda

Hello, when using revogrid we use a variety of custom editors, the clipboard function is in conflict with the way we save our data, it could be nice to have a prop to control when the clipboard should be enabled.

Also in this PR I added a condition to only do the custom paste when the editor is closed, which is the normal behavior of sheets or excel.

Have a nice day.

2021-02-24 23:23 UTC, revolist commented on src/components/revo-grid/revo-grid.tsx
> +  @Prop() useClipboard: boolean = false;
We need to make it true by default, 'coz other users who used to have it enabled will suffer from it.

2021-02-24 23:23 UTC, revolist requested changes
Please change from false to true by default. Thank you for the update.

2021-02-25 03:06 UTC, leyenda commented
I am sorry, I was testing and left the value as false by mistake, even in the docs I put the intended value jeje.
Already pushed the change.

2021-02-25 13:11 UTC, revolist commented
@leyenda, just fyi docs autogenerated. You don't have to fix them 👍

2021-02-25 13:15 UTC, revolist approved these changes
Thank you for the update. Feel free to contact us for any change.

2021-02-25 13:16 UTC, merged